### ISSUE TITLE
On some messaging apps the bitmap is shared as a File

### ISSUE THREAD

**Issue by ll24llll** [DigitalStrawberry/ANE-Share#12]
Hi, on some messaging apps like _Telegram_ there are 2 ways to share an image:
1. As photo (which compresses the image and previews it normally as a photo)
2. Without Compression (which previews it as a document file, not a photo)
In the second case, no text or link can be attached to the message and the photo is previewed as a small thumbnail.

This ane works with the second approach on Telegram which users don't mean for sharing.

**Comment by marpies** [comment]
Unfortunately this behavior is out of our control as the selected application decides how it processes the shared data. When sharing images together with text, the mime type has to be set to the generic type `*/*`, and it is up to the selected application to provide support for such data.

**Comment by ll24llll** [comment]
Actually I don't know how it should interpret with applications, but the [DataShare](https://www.adobe.com/devnet/air/articles/datashare-native-extension.html) ane worked fine on Telegram. Unfortunately, it is not working on newer Androids.
By the way, thanks a lot for sharing your great works.

**Comment by marpies** [comment]
Did you try sharing only images using our ANE? This results in the first case you described when sharing to Telegram. It's only when you combine images with other file types, Telegram uses the second case and shows the images as file previews. Therefore I believe there's not much we can do about this.
