### ISSUE TITLE
Can't share bitmapData on Android

### ISSUE THREAD

**Issue by Dikyx** [DigitalStrawberry/ANE-Share#2]
Hello!
First, **thanks for the great work and for sharing** 👍 

Everything works perfectly on iOS.  Text and/or url sharing works fine on Android too.

## The issue:
When I try to share bitmapData on Android, the system sharing popup won't show and none of the 3 events are fired.

### _Does anyone have the same problem?_
Please note I tried on two different Android devices and two different Android versions.
I may be doing something wrong, but I don't think so because the same code works fine on iOS.

## Here's the code I used to test the ANE:
```
package {

import com.digitalstrawberry.ane.share.Share;
import com.digitalstrawberry.ane.share.SharedData;
import com.digitalstrawberry.ane.share.events.ShareEvent;

import flash.display.Bitmap;
import flash.display.Sprite;

public class Main extends Sprite {

    [Embed(source="/../assets/test.png")]
    private static var SHARED_IMAGE:Class;

    private var bitmapTest:Bitmap = new SHARED_IMAGE();

    public function Main() {
        Share.instance.addEventListener(ShareEvent.COMPLETE, onSharingComplete);
        Share.instance.addEventListener(ShareEvent.CANCEL, onSharingCancel);
        Share.instance.addEventListener(ShareEvent.ERROR, onSharingError);

        var sharedImage:SharedData = new SharedData(bitmapTest.bitmapData);
        var sharedText:SharedData = new SharedData("Lorem ipsum dolor sit amet, mel et dolores quaestio.");
        var sharedLink:SharedData = new SharedData("https://github.com/DigitalStrawberry/ANE-Share");
        sharedLink.shareWithFacebook = false;

        var sharedItems:Vector.<SharedData> = new <SharedData>[sharedImage, sharedText, sharedLink]; // DOESN'T WORK ON ANDROID
        //var sharedItems:Vector.<SharedData> = new <SharedData>[sharedImage]; // DOESN'T WORK
        //var sharedItems:Vector.<SharedData> = new <SharedData>[sharedText, sharedLink]; // WORKS FINE

        Share.instance.share(sharedItems);
        trace("blbl");
    }

    private function onSharingError(event:ShareEvent):void {
        trace("ANE SHARE : Error");
    }

    private function onSharingCancel(event:ShareEvent):void {
        trace("ANE SHARE : Cancel");
    }

    private function onSharingComplete(event:ShareEvent):void {
        trace("ANE SHARE : Complete");
    }
}
}
```

**Comment by marpies** [comment]
Please double check the `{APP_PACKAGE_NAME}` that you set in your Android manifest XML. It must match your app id and remember it is prefixed with `air.` by default.

We've updated the code a bit to make sure an error is dispatched when the manifest is invalid. You can check the `errorMessage` property of the received event, so please try the latest release and let us know your results.

**Comment by Dikyx** [comment]
Thank you for your quick reply.
The problem was indeed coming from my `{APP_PACKAGE_NAME}`. As you guessed, I forgot to add the `air.` prefix in front of my app id. My bad!

Thanks to your code update, the `ERROR` event is now received when the `air.` prefix is missing.
`errorMessage = "Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"`

**Comment by scaryama** [comment]
I'm same `ERROR`

`errorMessage:Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)'on a null object reference`

**Comment by scaryama** [comment]
I got it!
My misstake

![image](https://user-images.githubusercontent.com/4054931/47108442-9d38dc00-d286-11e8-8f5a-69d2dbcfb169.png)

![image](https://user-images.githubusercontent.com/4054931/47107550-98732880-d284-11e8-854d-dc787abce073.png)
