### ISSUE TITLE
change sharing application problem

### ISSUE THREAD

**Issue by benkhachouch** [DigitalStrawberry/ANE-Share#4]
thanks for this extension.
when I share the first time with an application like instagram, for example, the other times that I can not change my sharing application, I'm stuck on instagram, unless I reset the application options on my mobile Android.

**Comment by ecornbower** [comment]
@benkhachouch Thanks for reaching out. Our staff is out on Christmas break but we'll be happy to address this when we're back in January.

@marpies I've also noticed this on some devices. Do you know if this is device specific to Android or something wrong with the ANE?

**Comment by marpies** [comment]
@benkhachouch Thanks for pointing this out. We've made some changes, so the last selected application should not be remembered.

**Comment by benkhachouch** [comment]
Thanks you very much!

Le 2 janv. 2018 22:00, "Marcel Piestansky" <notifications@github.com> a
écrit :

@benkhachouch <https://github.com/benkhachouch> Thanks for pointing this
out. We've made some changes, so the last selected application should not
be remembered.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DigitalStrawberry/ANE-Share/issues/4#issuecomment-354874103>,
or mute the thread
