### ISSUE TITLE
Receive files from other applications?

### ISSUE THREAD

**Issue by argonauta-studio** [DigitalStrawberry/ANE-Share#8]
Hello,
thanks for your work, much appreciated.
Since it seems that this extension does not enable the Air app to receive files from other applications via share, I was wondering how this can be achieved.

**Comment by marpies** [comment]
Please try looking around for other ANEs to enable this functionality. Our ANE was never meant to support this feature and we don't currently plan to implement that.

**Comment by argonauta-studio** [comment]
Ok. Thank you.
