### ISSUE TITLE
intent setType

### ISSUE THREAD

**Issue by argonauta-studio** [DigitalStrawberry/ANE-Share#9]
Hello,
is there a way to set the mime type for the share intent? 
My application would need to send a csv file which basically is just text. 
With the extension "csv" however the sharing does not work as  expected:
The "Messaging" app says: "failed to load attachment".
If I change the extension to "txt" however, the app accepts, but does not show an attachment. 
In the mail app all works well. 
Is the solution out of the extensions scope? 

thanks!

**Comment by marpies** [comment]
We've added the option to set custom MIME type on the `ShareOptions` object:

```as3
var options:ShareOptions = new ShareOptions();
options.mimeType = "text/csv";
```

Note some apps may still deny the attachments even if the correct MIME type is set.

**Comment by argonauta-studio** [comment]
Thank you.
